export const ENEMY_NAMES = {
  vikings: [
    { name: 'Ceifador do Fiorde' },
    { name: 'Guardião das Runas' },
    { name: 'Berserker do Arado' },
    { name: 'Escudeiro Gélido' },
    { name: 'Camponês Vigilante' },
    { name: 'Batedor de Neve' },
    { name: 'Runomante Rural' },
    { name: 'Guerreiro das Geadas' },
    { name: 'Ferreiro do Norte' },
    { name: 'Místico da Colheita' },
    { name: 'Raider do Grão' },
    { name: 'Defensor do Fiorde' },
    { name: 'Sentinela do Arpão' },
    { name: 'Martelo das Planícies' },
    { name: 'Ceifeira Ágil' },
    { name: 'Guardião da Aldeia' },
    { name: 'Batalhador do Cais' },
    { name: 'Escudeiro da Aurora' },
    { name: 'Jarl da Tempestade', boss: true },
    { name: 'Lorde da Colheita Sombria', boss: true },
  ],
  animais: [
    { name: 'Lobo Cinzento Alfa' },
    { name: 'Urso do Gelo' },
    { name: 'Javali das Neves' },
    { name: 'Coruja Vigilante' },
    { name: 'Serpente de Fjörnburg' },
    { name: 'Lince Escamado' },
    { name: 'Caribu Rúnico' },
    { name: 'Falcão da Aurora' },
    { name: 'Texugo Ártico' },
    { name: 'Raposa do Norte' },
    { name: 'Bode Rochoso' },
    { name: 'Corvo de Odin' },
    { name: 'Alce Perenne' },
    { name: 'Foca das Geleiras' },
    { name: 'Lobo Sombrio' },
    { name: 'Ursão Guardião' },
    { name: 'Bisão Boreal' },
    { name: 'Esquilo Rápido' },
    { name: 'Fenrir Desperto', boss: true },
    { name: 'Urso Rúnico Antigo', boss: true },
  ],
  pescadores: [
    { name: 'Arpoador Tempestuoso' },
    { name: 'Marinheiro do Gelo' },
    { name: 'Grumete das Ondas' },
    { name: 'Vigia do Farol' },
    { name: 'Caçador de Sereias' },
    { name: 'Navegador das Brumas' },
    { name: 'Corsário do Maelstrom' },
    { name: 'Curandeiro do Mar' },
    { name: 'Sentinela do Convés' },
    { name: 'Bardo do Porto' },
    { name: 'Escudeiro do Cais' },
    { name: 'Capitão das Marés' },
    { name: 'Lançador de Redes' },
    { name: 'Contrabandista do Fiorde' },
    { name: 'Pescador de Runas' },
    { name: 'Vigia das Profundezas' },
    { name: 'Guardião das Docas' },
    { name: 'Caçador de Tesouros' },
    { name: 'Senhor do Maelstrom', boss: true },
    { name: 'Kraken do Fiorde', boss: true },
  ],
  floresta: [
    { name: 'Guardião Musgoso' },
    { name: 'Raposa da Névoa' },
    { name: 'Cervo Rúnico' },
    { name: 'Coruja Mensageira' },
    { name: 'Lobo da Mata' },
    { name: 'Fada das Folhas' },
    { name: 'Javali Voraz' },
    { name: 'Treant dos Espinhos' },
    { name: 'Espírito do Carvalho' },
    { name: 'Sábio do Musgo' },
    { name: 'Guardião da Clareira' },
    { name: 'Lince da Sombra' },
    { name: 'Bardo das Árvores' },
    { name: 'Druida dos Cogumelos' },
    { name: 'Corvo Observador' },
    { name: 'Serpente do Bosque' },
    { name: 'Centauro das Brumas' },
    { name: 'Javali de Runas' },
    { name: 'Avatar do Carvalho Ancestral', boss: true },
    { name: 'Espírito do Cervo Estelar', boss: true },
  ],
  convergentes: [
    { name: 'Neófito Prismático' },
    { name: 'Assimilador Rúnico' },
    { name: 'Guardião Quimérico' },
    { name: 'Raider Metamorfo' },
    { name: 'Lince Metamórfico' },
    { name: 'Totem Absorvente' },
    { name: 'Arauto da Aurora' },
    { name: 'Sombra Rúnica' },
    { name: 'Guerreiro Sincrético' },
    { name: 'Discípulo Maleável' },
    { name: 'Sentinela Vórtice' },
    { name: 'Tecelão Cambiante' },
    { name: 'Eco Mutante' },
    { name: 'Bruto Assimilador' },
    { name: 'Sábio Prismal' },
    { name: 'Avatar Mutagênico' },
    { name: 'Capataz de Runas' },
    { name: 'Essência Convergente' },
    { name: 'Catalisador da Aurora', boss: true },
    { name: 'Entidade Transmutante', boss: true },
  ],
};
